config/routes.rb
Rails.application.routes.draw do

	devise_for :users
	root to: 'infos#index'
	get 'home', to: 'infos#index'
	get 'dashboard', to: 'infos#dashboard', as: 'dashboard'
	resources :infos, except: [:delete,:update]
	resources :addstartups, only: [:new,:create]

end

app/models/addstartup.rb
class Addstartup < ActiveRecord::Base
end

app/models/info.rb
class Info < ActiveRecord::Base

	has_attached_file :image, styles: {large: "600*600>", medium: "300*200>",thumb: "220*140%"}
	validates_attachment_content_type :image , content_type: /\Aimage\/.*\Z/
	validates :image, presence: true
	validates :title, presence: true
	validates :description , presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/addstartups_controller.rb
class AddstartupsController < ApplicationController

	def new
		@startup=Addstartup.new
	end

	def create
		@startup=Addstartup.create(startup_params)

	end


	#private params setup for create controller.
	private
	def startup_params
		params.require(:addstartup).permit(:title,:founders,:description)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
	before_action :authenticate_user!, only: [:new,:admin]
	def new
		@info=Info.new
	end

	def create
		@info=Info.create(info_params)
		if @info.save 
			redirect_to infos_path
		else 
			render new_info_path
		end
		

	end

	def index 
		@info=Info.all.paginate(page: params[:page], per_page:12)
		@this_month=Info.where(:created_at => Time.now.beginning_of_month..Time.now.end_of_month)
	end


	def dashboard
	end

	def show
		@info=Info.find(params[:id])
	end


	private 
	def info_params
		params.require(:info).permit(:title,:founders,:description,:image)
	end


end

app/helpers/addstartups_helper.rb
module AddstartupsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/addstartups/new.html.erb
<div class="add-startup">
<div class="container">
	

<div class="col-md-8 col-md-offset-2 startup-form">
	
		<h2 class="text-center"> Add New Startups</h2>

	<%= form_for(@startup) do |f| %>
	<p class="text-center "> Startup Info</p>
	
	<div class="field">
		<%=f.label :title %>
		<%= f.text_field :title ,class: "form-control" %>

<div class="field">
	<%= f.label :founders %>
	<%= f.text_field :founders ,class: "form-control"%>
</div>
	</div>



<div class="field">
	<%= f.label :description %>
	<%= f.text_area :description,class: "form-control",rows: 6 %>
</div>
<br>
<p class="text-center "> Socail Media</p>
<div class="field">
	<%= f.label "facebook Link"%>
	<%= f.text_field :facebook,class: "form-control",rows: 6 %>
</div>

<br>

<p class="text-center"> Optional Fields</p>

<div class="field">
	<%= f.label "Number of employees"%>
	<%= f.text_field :noemployees ,class: "form-control",placeholder: "Leave blank if you dont want to submit"%>
</div>

<br>
<br>
<br>
<br>
<br>

<div class="action">
	<%= f.submit "submit", class: "btn btn-lg btn-primary pull-right"%>
</div>

<% end %>
	</div>


	
</div>
	</div>

app/views/infos/dashboard.html.erb
<div class="container">
	
	<h1>Dashboard</h1>
</div>

app/views/infos/index.html.erb
<div class="headerimage" style="background-color:#1dd2af;height:290px">
	<div class="container">
		<div class="col-md-12 col-xs-12 col-sm-12"></div>
		<h2 class="text-center" style="font-family:Helvetica;color:#fff;">Handpicked Malaysian Startups</h2>
		
		<div class="col-md-6 col-md-offset-5">
			
			<p style="color:#fff"> Curated for you....</p>
			<p style="color:#fff"> Submit your startup now </p>

			<%= link_to("Submit your startup", new_addstartup_path,class: "btn btn-lg btn-success") %> 
		</div>
	</div>
</div>
</div>


<div class="col-md-12">
	<h2 class="text-center">Newly added</h2>
	<% @this_month.each do |new| %>
	<div class="col-md-2" style="background-color:#27ae60;margin:40px;border-radius:30px;height:60px;">
	
	<h4 class="text-center">
		
	 <%= new.title %>
	</h4>
		
	</div>

	<% end %>

</div>

<div class="main">
	
	<div class="container container-main">
	<h2 class="text-center">Startups</h2>
		<div class="row" style="margin-top:30px;">
			<% @info.each do |info| %>

			<div class="col-md-3 col-xs-12 col-sm-12">
				<div class="panel panel-success startupinfo">

					<div class="panel-heading">
						<%= info.title %>
					</div>


					<div class="panel-body">

						<%= image_tag info.image(:thumb),class: 'img-thumb' %>
						<p>Founders: <%= info.founders %> </p>
						<hr>
						<p>Info:  <%= info.description %> </p>
						<p> <%= link_to("more", info_path(info)) %></p>
						

					</div>



				</div>


			</div>

			<% end %>

			<div class="col-md-12  div-pagination">
				<%= will_paginate @info %>
			</div>

		</div>





	</div>



</div>


<div class="content-suscribe">
	<div class="col-md-5 col-md-offset-3">
		
		<p class="suscribe-heading">  
			Subscribe to Amazing Malaysian Startup Stories..
		</p>


		<div class="form-group">
			<label class="sr-only" for="">label</label>
			<input type="email" class="form-control" id="" placeholder="example@example.com">
		</div>

		<div class="col-md-6 col-md-offset-3">
			
			<button  class="btn btn-primary text-center">Submit</button>


			<button class="btn btn-warning text-center" data-toggle="modal" data-toggle="modal" data-target="#myModal">Why?</button>

		</div>


	</div>
</div>




<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Why Suscribe ?</h4>
			</div>
			<div class="modal-body">
				<ul>
					<li>Get notified when new startup is added</li>
					<li>Get stories delivered right in your inbox</li>
					<li>Get to know about amazing things happening in Malaysia</li>
					<li>Get to know malaysian Tech ecosystem.</li>
				</ul>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Yes.I'm up</button>
			</div>
		</div>
	</div>
</div>

app/views/infos/new.html.erb
<div class="col-md-4 col-md-offset-4 ">

	<% if user_signed_in? %>
	<h2> Add new startups</h2>	
	
	<%= form_for @info ,html: {multipart: true} do |f| %>

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title , class: 'form-control'%>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.file_field :image,class: 'form-control' %>
	</div>
	<br>

	<div class="field">
		<%= f.label  :founders %>
		<%= f.text_field :founders , class: 'form-control' %>
	</div>

	<div class="field">

		<%= f.label :description %>
		<%= f.text_area :description , class: 'form-control', rows:6%>
		
	</div>
	<br>

	<div class="actions">
		<%= f.submit "Submit" , class: 'btn btn-danger btn-block'%>
	</div>

	<% end %>

	<% end %>

</div>

<% if @info.errors.any? %>
    <div id="error_explanation">
      <p class="text-danger">

      <%= pluralize(@info.errors.count, "error") %> prohibited this post from being saved:
      </p>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



	

app/views/infos/show.html.erb
<div class="container">
	
<div class="show" style="min-height:690px;">
	
<div class="col-md-12" >
	<div class="col-md-2 ">
		<%= image_tag @info.image(:thumb),class: 'img-thumb' %>
	</div>
	
	<h1 class="text-center"> <%= @info.title %> </h1>

	<hr>

</div>

<div class="col-md-3" style="border:1px solid #e3e3e3;min-height:400px;">
	<h2>Founders</h2>
	<%= @info.founders %>
</div>


<div class="col-md-6  col-md-offset-2">
	

	<%= @info.description %>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Startupsinmalaysia</title>
	
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<div class="col-md-12 navimage">
<div class="col-md-offset-5">
	
	<%= image_tag("startups in malaysia beta.png",class:'ac-nav-image' )%>
</div>
</div>




	<div class="row" style="background-color:#fff">
		
	<div class="col-md-offset-3 hidden-xs hidden-sm" style="margin-top:30px;">
		
			<ul class="nav navbar-nav">
				<li class="active">
					<%= link_to("Home", root_path) %>
				</li>
				
				<li>
					<%= link_to("Partners") %>
				</li>

				<li>
					<%= link_to("News") %>
				</li>
				
				<li>
					<%= link_to("Say hi") %>
				</li>

				<li> <%= link_to("Add new", new_addstartup_path) %> </li>

				<li>
					<%= link_to("Social enterprise") %>
				</li>

				<% if current_user %>
				<li>    
					<%= link_to("profile", "#", class: 'text-email') %> 
				</li>

				<% end %>

				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown ">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"> <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<% if current_user %>
							<li> <%= link_to("Logout", destroy_user_session_path, method: :delete ) %></li>
							<li><a href="#">profile</a></li>
							<li> <%= link_to("Dashboard", dashboard_path ) %>
							<li><%= link_to("New ", new_info_path) %></li>
								<% else %>
								<li> <%= link_to("login", new_user_session_path) %> </li>	
								<%end %>

							</ul>
						</li>
					</ul>

				</ul>




			
		
	</div>
	</div>



		<div class="col-md-5 col-md-offset-4">
			<p class="notice"> <%= notice %> </p>
			<p class="alert">  <%= alert %> </p>
		</div>
		
		

		
		<%= yield %>


		<div class="footer col-md-12 header-image-wrapper">
			<div class="col-md-4">
				<p> &copy Copyright Startups In Malaysia 2015 </p> 
			</div>

			<div class="col-md-4">
				<p>Contact Us</p>
				<p> Say hi to us: hello@startupsinmalaysia.com </p> 
			</div>

			<div class="col-md-4">
			<div class="container">
				
				<div class="fb-page" data-href="https://www.facebook.com/pages/190Degrees/1620098144893351" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="false"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/pages/190Degrees/1620098144893351"><a href="https://www.facebook.com/pages/190Degrees/1620098144893351">190Degrees</a></blockquote></div></div>

				
			</div>
		</div>

		</div>

		

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.4";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


	</body>
	</html>